name: "Update Bot"
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.**'
      - 'data/*'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.**'
      - 'data/*'
  schedule:
    - cron: '*/5 * * * *'
      
jobs:
  update-data:
    name: Update bot
    runs-on: "macos-latest"
    steps:
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
      - name: Setup - Checkout repo
        uses: actions/checkout@v2
      - name: "Data - Retrieve data"
        run: |
          source('R/data_check.R')
        shell: Rscript {0}
      - name: "Data - Check whether data was updated"
        id: check-whether-updated
        run: |
          UPDATE_MSG=$(cat /tmp/update.txt)
          LAST_DATE=$(cat /tmp/last_date.txt)
          IS_UPDATED=0; [ "UPDATE_MSG" == "no_update" ] || IS_UPDATED=1
          echo $UPDATE_MSG
          echo LAST_DATE
          echo $IS_UPDATED
          echo "::set-output name=UPDATE_MSG::UPDATE_MSG"
          echo "::set-output name=LAST_DATE::LAST_DATE"
          echo "::set-output name=IS_UPDATED::$IS_UPDATED"
      - name: "Setup - Install Packages"
        run: |
          install.packages('twitteR')
          install.packages('dplyr')
          install.packages('here')
          install.packages('remotes')
          remotes::install_github("hadley/emo")
          install.packages('stringr')
          install.packages('countrycode')
          install.packages('scales')
        shell: Rscript {0}
        if:  ${{ steps.check-whether-updated.outputs.IS_UPDATED == 1 }}
      - name: "Bot - Run"
        run: Rscript 'R/bot.R'
        if:  ${{ steps.check-whether-updated.outputs.IS_UPDATED == 1 }}
        env:
          consumer_key: ${{ secrets.CONSUMER_KEY }}
          consumer_secret: ${{ secrets.CONSUMER_SECRET }}
          token: ${{ secrets.TOKEN }}
          secret: ${{ secrets.SECRET }}
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bot Routine