  
name: "Update Bot"
on: 
  # push:
  schedule:
  - cron: '1 */17 * * *'
  
jobs:
  update-data:
    name: Update bot
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
      - name: "Setup - Install Packages"
        run: |
          install.packages('twitteR')
          install.packages('remotes')
          remotes::install_github("hadley/emo")
          install.packages('dplyr')
          install.packages('stringr')
          install.packages('countrycode')
          install.packages('scales')
          install.packages('here')
        shell: Rscript {0}
      - name: "Bot - Run"
        run: Rscript 'R/bot.R'
        env:
          consumer_key: ${{ secrets.CONSUMER_KEY }}
          consumer_secret: ${{ secrets.CONSUMER_SECRET }}
          token: ${{ secrets.TOKEN }}
          secret: ${{ secrets.SECRET }}
      - name: Commit results
        run: |
          git add -A || echo "No changes to commit"
          git commit --allow-empty -m 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"