  
name: "Update Bot"
on: 
  schedule:
  - cron: '30  */8 * * *'
  push:
    branches:
      - "master"
      
jobs:
  update-data:
    name: Update bot
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
      - name: "Setup - Install Packages"
        run: |
          install.packages('twitteR')
          install.packages('remotes')
          remotes::install_github("hadley/emo")
          install.packages('dplyr')
          install.packages('stringr')
          install.packages('countrycode')
          install.packages('scales')
          install.packages('here')
        shell: Rscript {0}
      - name: "Bot - Run"
        run: Rscript 'R/bot.R'
        env:
          consumer_key: ${{ secrets.CONSUMER_KEY }}
          consumer_secret: ${{ secrets.CONSUMER_SECRET }}
          token: ${{ secrets.TOKEN }}
          secret: ${{ secrets.SECRET }}
      - name: "Commit"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bot Routine